
let firstAids = [
    {
        name: "Bleeding",
        img_src: "https://www.verywellhealth.com/thmb/S7Pp-oYhwU-A86gseGC41RDFM24=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-525386797-5a6a1eccfa6bcc003690b97f.jpg",
        information: [
            "Call 911 or your local emergency number if the wound is deep or you're not sure how serious it is. Don't move the injured person except if needed to avoid further injury.",
            "Before checking for the source of the wound, put on disposable gloves and other personal protective equipment if you have them.",
            "Remove any clothing or debris from the wound. Look for the source of the bleeding. There could be more than one injury. Remove any obvious debris but don't try to clean the wound. Don't remove large or deeply embedded objects, and don't probe the wound.",
            "Stop the bleeding. Cover the wound with sterile gauze or a clean cloth. Press on it firmly with the palm of your hand until bleeding stops. But don't press on an eye injury or embedded object. Don't press on a head wound if you suspect a skull fracture.",
            "Wrap the wound with a thick bandage or clean cloth and tape. Lift the wound above heart level if possible.",
            "Help the injured person lie down. If possible, place the person on a rug or blanket to prevent loss of body heat. Elevate the feet if you notice signs of shock, such as weakness, clammy skin or a rapid pulse. Calmly reassure the injured person.",
            "Add more bandages as needed. If the blood seeps through the bandage, add more gauze or cloth on top of the existing bandage. Then keep pressing firmly on the area.",
            "Tourniquets: A tourniquet is effective in controlling life-threatening bleeding from a limb. If needed, apply a commercially made tourniquet if it's available and you're trained in how to use it. Don't use an improvised tourniquet, such as a scarf or a belt.",
            "When emergency help arrives, tell them how long the tourniquet has been in place.",
            "Keep the person still. If you're waiting for emergency help to arrive, try to keep the injured person from moving.",
            "If you haven't called for emergency help, get the injured person to an emergency room as soon as possible.",
            "Wash your hands. After helping the injured person, wash your hands, even if it doesn't look like any blood got on your hands."],
        yt_url: "https://youtube.com/embed/NxO5LvgqZe0"
    },
    {
        name: "Choking",
        img_src: "https://www.verywellhealth.com/thmb/OvYCTOPiSh8Kldk3o1yhd475280=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-136811278-664fedac86fc431d84ab156fdfeda4e4.jpg",
        information: [
            "Choking happens when an object lodges in the throat or windpipe blocking the flow of air. In adults, a piece of food is usually to blame. Young children often choke on small objects. Choking is life-threatening. It cuts off oxygen to the brain. Give first aid as quickly as possible if you or someone else is choking.",
            "Watch for these signs of choking:",
            "One or both hands clutched to the throat",
            "A look of panic, shock or confusion",
            "Inability to talk",
            "Strained or noisy breathing",
            "Squeaky sounds when trying to breathe",
            "Cough, which may either be weak or forceful",
            "Skin, lips and nails that change color turning blue or gray",
            "Loss of consciousness",
            "If a choking person can cough forcefully, let the person keep coughing.",
            "Coughing might naturally remove the stuck object.",
            "If a person can't cough, talk, cry or laugh forcefully, give first aid to the person.",
            "The American Red Cross recommends the following steps:",
            "Give five back blows. Stand to the side and just behind a choking adult. For a child, kneel down behind. Place your arm across the person's chest to support the person's body. Bend the person over at the waist to face the ground. Strike five separate times between the person's shoulder blades with the heel of your hand.",
            "Give five abdominal thrusts. If back blows don't remove the stuck object, give five abdominal thrusts, also known as the Heimlich maneuver.",
            "Alternate between five blows and five thrusts until the blockage is dislodged.",
            "Some sources only teach the abdominal thrust. It's OK not to use back blows if you haven't learned the back-blow technique. Both approaches are acceptable for adults and children older than age 1.",
            "To give abdominal thrusts to someone else:",
            "Stand behind the person. For a child, kneel down behind. Place one foot slightly in front of the other for balance. Wrap your arms around the waist. Tip the person forward slightly.",
            "Make a fist with one hand. Put it just above the person's navel.",
            "Grasp the fist with the other hand. Press into the stomach, also called the abdomen, with a quick, upward thrust — as if trying to lift the person up. For a child, use gentle yet firm pressure to avoid damaging the internal organs.",
            "Give five abdominal thrusts. Check if the blockage has been removed. Repeat as needed.",
            "If you're the only rescuer, give back blows and abdominal thrusts first. Then call 911 or your local emergency number for help. If another person is there, have that person call for help while you give first aid.",
            "If the person becomes unconscious, start standard cardiopulmonary resuscitation (CPR) with chest compressions and rescue breaths.",
            "If the person is pregnant or if you can't get your arms around the stomach, give chest thrusts:",
            "Put your hands at the base of the breastbone, just above the joining of the lowest ribs.",
            "Press hard into the chest with a quick thrust. This is the same action as the Heimlich maneuver.",
            "Repeat until the blockage is removed from the airway.",
            "To clear the airway of an unconscious person:",
            "Lower the person onto the floor, with the back on the floor and arms to the sides.",
            "Clear the airway. If you can see the object, reach a finger into the mouth to sweep out the object. Never finger sweep if you can't see the object. You risk pushing the blockage deeper into the airway. This is very risky with young children.",
            "Begin CPR if the person still doesn't respond. If the airway is still blocked, use chest compressions such as those that are used in CPR to remove the stuck object. Only use two rescue breaths per cycle. Recheck the mouth regularly for the object",
            "To clear the airway of a choking infant younger than age 1:",
            "Sit and hold the infant facedown on your forearm. Rest your forearm on your thigh. Hold the infant's chin and jaw to support the head. Place the head lower than the trunk.",
            "Thump the infant gently but firmly five times on the middle of the back. Use the heel of your hand. Point your fingers up so that you don't hit the back of the infant's head. Gravity and the back thumps should release the blockage.",
            "Turn the infant faceup on your forearm if breathing hasn't started. Rest your arm on your thigh. Place the infant's head lower than the trunk.",
            "Give five gentle but firm chest compressions with your fingers. Place two fingers just below the nipple line. Press down about 1 1/2 inches. Let the chest rise between each compression.",
            "Repeat the back thumps and chest compressions if breathing doesn't start. Call for emergency medical help.",
            "Begin infant CPR if the airway is clear but the infant doesn't start breathing."
        ],
        yt_url: "https://youtube.com/embed/h_vSEviFXIo"
    },
    {
        name: "Burns",
        img_src: "https://libraot.com/wp-content/uploads/2020/07/hand-burns-0311-1280x500-1.jpg",
        information: [
            "Stop the burning process as soon as possible. This may mean removing the person from the area, dousing flames with water, or smothering flames with a blanket. Do not put yourself at risk of getting burnt as well.",
            "Remove any clothing or jewellery near the burnt area of skin, including babies' nappies. But do not try to remove anything that's stuck to the burnt skin, as this could cause more damage.",
            "Cool the burn with cool or lukewarm running water for 20 minutes as soon as possible after the injury. Never use ice, iced water, or any creams or greasy substances like butter.",
            "Keep yourself or the person warm. Use a blanket or layers of clothing, but avoid putting them on the injured area. Keeping warm will prevent hypothermia, where a person's body temperature drops below 35C (95F). This is a risk if you're cooling a large burnt area, particularly in young children and elderly people.",
            "Cover the burn with cling film. Lay the cling film over the burn, rather than wrapping it around a limb. A clean, clear plastic bag can be used for burns on your hand.",
            "Treat the pain from a burn with paracetamol or ibuprofen. Always check the manufacturer's instructions when using over-the-counter medication. Children under 16 years of age should not be given aspirin.",
            "Raise the affected area, if possible. This will hep to reduce swelling."
        ],
        yt_url: "https://youtube.com/embed/B51VgoEZcDs"
    },
    {
        name: "Nosebleed",
        img_src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOip4ZM4oDgDjSEFt2EIjeNvYyCnwN29xlPw&usqp=CAU",
        information: [
            "Nosebleeds, also called epistaxis (ep-ih-STAK-sis), are common. They happen when the tender blood vessels in the nose break. Common nosebleed causes can include changes of season, dryness, scratching, some medicines and injuries. People on blood thinners may have worse nosebleeds than do others. Most often nosebleeds are only annoying and not a true medical problem. But they can be both.",
            "Seek emergency care if:",
            "Nosebleeds involve a greater than expected amount of blood.",
            "Nosebleeds last longer than 30 minutes.",
            "You feel faint or lightheaded.",
            "The nosebleed follows a fall or an accident. Bleeding after a fall or an injury to the head or face could mean that you have broken the nose.",
            "Self-care for a common nosebleed",
            "Sit up and lean forward. Keep the head up. Lean forward so the blood doesn't go down the throat. This could cause you to choke or have an upset stomach.",
            "Gently blow your nose. This will clear any blood clots.",
            "Pinch the nose. Use the thumb and a finger to pinch both nostrils shut. Breathe through the mouth. Keep pinching for 10 to 15 minutes. Pinching puts pressure on the blood vessels and helps stop the blood flow.",
            "If the bleeding doesn't stop, pinch the nose again for up to 15 minutes. Don't let go for at least five minutes even to check if the bleeding has stopped. Seek emergency care if the bleeding doesn't stop after the second try.",
            "Prevent another nosebleed. Don't pick or blow the nose. And don't drop the head below the heart or lift anything heavy for many hours. Gently put a saline gel (Ayr), antibiotic ointment (Neosporin) or petroleum jelly (Vaseline) on the inside of the nose. Put most of the salve on the middle part of the nose, also called the septum. Steam, humidifiers or an ice pack across the bridge of the nose also may help.",
            "If you have another nosebleed, try first-aid steps again. This time, spray both sides of the nose with a nasal spray that has oxymetazoline in it (Afrin). Do this after blowing the nose. Then pinch the nose again. Seek medical help if the bleeding does not stop."
        ],
        yt_url: "https://youtube.com/embed/S-IlqmRoaZc"
    },
    {
        name: "Sunburn",
        img_src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKqfh5md3Ev_gG_N9NB-_kI94Oqxh7rUKxf9fNbntVZlhrX5cV9Sz6kCydgelkXgfFH_Y&usqp=CAU",
        information: [
            "If you have been sunburned, you will notice the signs and symptoms within a few hours after too much sun. The affected skin will be painful, inflamed and hot to the touch. Blisters might develop. You may also experience headache, fever or nausea.",
            "Seek immediate medical care if you are sunburned and experience:",
            "A fever over 103 degrees Fahrenheit (39.4 degrees Celsius) with vomiting",
            "Confusion",
            "An infection in the sunburned area",
            "Dehydration",
            "If you have a sunburn",
            "First aid might offer some relief from the discomfort of sunburn:",
            "Take a pain reliever such as ibuprofen (Advil, Motrin IB, others) or acetaminophen (Tylenol, others) as soon as possible after getting too much sun. Or try a gel pain reliever that you rub on the skin.",
            "Cool the skin. Apply to the affected skin a clean towel dampened with cool tap water. Or take a cool bath with. Add about 2 ounces (60 grams) of baking soda to the tub. Cool the skin for about 10 minutes several times a day.",
            "Apply a moisturizer, lotion or gel. An aloe vera lotion or gel or calamine lotion can be soothing. Try cooling the product in the refrigerator before applying. Avoid products that contain alcohol.",
            "Drink extra water for a day to help prevent dehydration.",
            "Leave blisters alone. An intact blister can help the skin heal. If a blister does break, trim off the dead skin with a clean, small scissors. Gently clean the area with mild soap and water. Then apply an antibiotic ointment to the wound and cover it with a nonstick bandage.",
            "Protect yourself from further sun exposure while your skin heals from the sunburn.",
            "Apply a soothing medicated cream. For mild to moderate sunburn, apply nonprescription 1% hydrocortisone cream to the affected area three times a day for three days. Try cooling the product in the refrigerator before applying.",
            "Treat sunburned eyes by covering them with a clean towel dampened with cool tap water. Don't wear contacts until your eye symptoms have gone away. Don't rub your eyes.",
            "Seek medical care for large blisters or those that form on the face, hands or genitals. Also seek medical help if you have worsening pain, headache, confusion, nausea, fever, chills, eye pain or vision changes, or signs of infection, such as blisters with swelling, pus or streaks."
        ],
        yt_url: "https://youtube.com/embed/-l8a3Bc3jRA"
    },
    {
        name: "Splinter",
        img_src: "https://sa1s3optim.patientpop.com/assets/images/provider/photos/2006213.jpg",
        information: [
            "You can usually safely remove a small foreign object — such as a wood splinter, thorn, fiberglass or glass — that's just under the surface of the skin:",
            "Wash your hands and clean the area well with soap and water.",
            "Use tweezers cleaned with rubbing alcohol to remove the object. Use a magnifying glass to help you see better.",
            "If the object is under the surface of the skin, sterilize a clean, sharp needle by wiping it with rubbing alcohol. Use the needle to gently break the skin over the object and lift up the tip of the object.",
            "Use a tweezers to grab the end of the object and remove it.",
            "Wash the area again and pat dry. Apply petroleum jelly or an antibiotic ointment.",
            "Seek prompt medical help for a foreign object that seems to be more deeply embedded in the skin or muscle. Follow these precautions and steps first:",
            "Don't try to remove the object. Doing so could cause further harm.",
            "Bandage the wound. First put a piece of gauze over the object. Then, if it helps, put clean padding around the object before binding the wound securely with a bandage or a piece of clean cloth. Take care not to press too hard on the object.",
            "In addition, seek medical help if:",
            "The object is hard to see (as with clear glass) or doesn't come out easily (as with a fishhook).",
            "The injury involves an eye or is close to an eye.",
            "The wound is deep or dirty and the injured person's last tetanus vaccination was more than five years ago. The doctor may recommend a booster."
        ],
        yt_url: "https://youtube.com/embed/L6crQ3nMLkI"
    },
    {
        name: "Fractures",
        img_src: "https://fractureclinic.com.au/wp-content/uploads/2020/02/Fracture-scaled.jpg",
        information: [
            "A fracture is a broken bone. It requires medical attention. If the broken bone is the result of major trauma or injury, call 911 or your local emergency number.",
            "Also call for emergency help if:",
            "The person is unresponsive, isn't breathing or isn't moving. Begin CPR if there's no breathing or heartbeat.",
            "There is heavy bleeding.",
            "Even gentle pressure or movement causes pain.",
            "The limb or joint appears deformed.",
            "The bone has pierced the skin.",
            "The extremity of the injured arm or leg, such as a toe or finger, is numb or bluish at the tip.",
            "You suspect a bone is broken in the neck, head or back.",
            "Don't move the person except if necessary to avoid further injury. Take these actions immediately while waiting for medical help:",
            "Stop any bleeding. Apply pressure to the wound with a sterile bandage, a clean cloth or a clean piece of clothing.",
            "Immobilize the injured area. Don't try to realign the bone or push a bone that's sticking out back in. If you've been trained in how to splint and professional help isn't readily available, apply a splint to the area above and below the fracture sites. Padding the splints can help reduce discomfort.",
            "Apply ice packs to limit swelling and help relieve pain. Don't apply ice directly to the skin. Wrap the ice in a towel, piece of cloth or some other material.",
            "Treat for shock. If the person feels faint or is breathing in short, rapid breaths, lay the person down with the head slightly lower than the trunk and, if possible, elevate the legs."
        ],
        yt_url: "https://youtube.com/embed/2v8vlXgGXwE"
    },
    {
        name: "Insect Bite/Sting",
        img_src: "https://i0.wp.com/post.healthline.com/wp-content/uploads/2022/09/tick-biting-body.jpg?w=1155&h=1528",
        information: [
            "Most insect bites and stings are mild and can be treated at home. They might cause itching, swelling and stinging that go away in a day or two. Some bites or stings can transmit disease-causing bacteria, viruses or parasites. Stings from bees, yellow jackets, wasps, hornets and fire ants might cause a severe allergic reaction (anaphylaxis).",
            "For mild reactions",
            "To treat a mild reaction to an insect bite or sting:",
            "Move to a safe area to avoid more bites or stings.",
            "Remove any stingers.",
            "Gently wash the area with soap and water.",
            "Apply a cloth dampened with cold water or filled with ice to the area of the bite or sting for 10 to 20 minutes. This helps reduce pain and swelling.",
            "If the injury is on an arm or leg, raise it.",
            "Apply to the affected area calamine lotion, baking soda paste, or 0.5% or 1% hydrocortisone cream. Do this several times a day until your symptoms go away.",
            "Take an anti-itch medicine (antihistamine) by mouth to reduce itching. Options include nonprescription cetirizine, fexofenadine (Allegra Allergy, Children's Allegra Allergy), loratadine (Claritin).",
            "Take a nonprescription pain reliever as needed.",
            "Seek medical care if the swelling gets worse, the site shows signs of infection or you don't feel well.",
            "When to seek emergency care",
            "Call 911 or your local medical emergency number if a child is stung by a scorpion or if anyone is having a serious reaction that suggests anaphylaxis, even if it's just one or two signs or symptoms:",
            "Trouble breathing",
            "Swelling of the lips, face, eyelids or throat",
            "Dizziness, fainting or unconsciousness",
            "A weak and rapid pulse",
            "Hives",
            "Nausea, vomiting or diarrhea",
            "Take these actions immediately while waiting for medical help:",
            "Ask whether the injured person is carrying an epinephrine autoinjector (EpiPen, Auvi-Q, others). Ask whether you should help inject the medication. This is usually done by pressing the autoinjector against the thigh and holding it in place for several seconds.",
            "Loosen tight clothing and cover the person with a blanket.",
            "Don't offer anything to drink.",
            "If needed, position the person to prevent choking on vomit."
        ],
        yt_url: "https://youtube.com/embed/YkUW3pquCF4"
    },
    {
        name: "Poisoning",
        img_src: "https://www.legalexaminer.com/wp-content/uploads/sites/244/2021/11/poison-skull-crossbones@large.jpg",
        information: [
            "Poisoning is injury or death due to swallowing, inhaling, touching or injecting various drugs, chemicals, venoms or gases. Many substances — such as drugs and carbon monoxide — are poisonous only in higher concentrations or dosages. Certain types of cleaners are only harmful if ingested, while others also emit toxic gases/fumes. Children are particularly sensitive to even small amounts of certain drugs and chemicals.",
            "How you treat someone who may have been poisoned depends on:",
            "The person's symptoms",
            "The person's age",
            "Whether you know the type and amount of the substance that caused poisoning",
            "There are two ways to get help from Poison Control in the U.S: online at www.poison.org or by calling 800-222-1222. Both options are free, confidential, and available 24 hours a day. It may help to place a refrigerator magnet or a visible sticker in your home with the poison control number. Poison control centers are excellent resources for poisoning information and, in many situations, may advise that in-home observation is all that's needed.",
            "When to suspect poisoning",
            "Poisoning signs and symptoms can mimic other conditions, such as seizure, alcohol intoxication, stroke and insulin reaction. Signs and symptoms of poisoning may include:",
            "Burns or redness around the mouth and lips",
            "Breath that smells like chemicals, such as gasoline or paint thinner",
            "Vomiting",
            "Difficulty breathing",
            "Drowsiness",
            "Confusion or other altered mental status",
            "If you suspect poisoning, be alert for clues such as empty pill bottles or packages, scattered pills, and burns, stains and odors on the person or nearby objects. With a child, consider the possibility that he or she may have applied medicated patches, taken prescription medications or swallowed a button battery.",
            "When to call for help",
            "Call 911 or your local emergency number immediately if the person is:",
            "Drowsy or unconscious",
            "Having difficulty breathing or has stopped breathing",
            "Uncontrollably restless or agitated",
            "Having seizures",
            "Known to have taken medications, or any other substance, intentionally or accidentally overdosed (in these situations the poisoning typically involves larger amounts, often along with alcohol)",
            "Call Poison Help at 800-222-1222 in the United States or your regional poison control center in the following situations:",
            "The person is stable and has no symptoms",
            "The person is going to be transported to the local emergency department",
            "Be ready to describe the person's symptoms, age, weight, other medications he or she is taking, and any information you have about the poison. Try to determine the amount ingested and how long since the person was exposed to it. If possible, have on hand the pill bottle, medication package or other suspect container so that you can refer to its label when speaking with the poison control center.",
            "What to do while waiting for help",
            "Take the following actions until help arrives:",
            "Swallowed poison. Remove anything remaining in the person's mouth. If the suspected poison is a household cleaner or other chemical, read the container's label and follow instructions for accidental poisoning.",
            "Poison on the skin. Remove any contaminated clothing using gloves. Rinse the skin for 15 to 20 minutes in a shower or with a hose.",
            "Poison in the eye. Gently flush the eye with cool or lukewarm water for 20 minutes or until help arrives.",
            "Inhaled poison. Get the person into fresh air as soon as possible.",
            "If the person vomits, turn his or her head to the side to prevent choking.",
            "Begin CPR if the person shows no signs of life, such as moving, breathing or coughing.",
            "Call Poison Help at 800-222-1222 in the United States or your regional poison control for additional instructions.",
            "Have somebody gather pill bottles, packages or containers with labels, and any other information about the poison to send along with the ambulance team.",
            "In the case of an opioid overdose",
            "If the person is at risk of overdose of opioid pain medication and naloxone (Narcan) is available, please administer. Increasingly, health care providers are giving people Narcan injectable prescriptions if they are at risk of overdose. Loved ones should be familiar with how to use them.",
            "Caution:",
            "Syrup of ipecac. Don't give syrup of ipecac or do anything to induce vomiting. Expert groups, including the American Association of Poison Control Centers and the American Academy of Pediatrics, no longer endorse using ipecac in children or adults who have taken pills or other potentially poisonous substances. No good evidence proves its effectiveness, and it often can do more harm than good.",
            "If you still have old bottles of syrup of ipecac in your home, throw them away.",
            "Button batteries. The small, flat batteries used in watches and other electronics — particularly the larger, nickel-sized ones — are especially dangerous to small children. A battery stuck in the esophagus can cause severe tissue burns.",
            "If you suspect that a child has swallowed one of these batteries, immediately take him or her for an emergency X-ray to determine its location. If the battery is in the esophagus, it will have to be removed. If it has passed into the stomach, it's usually safe to allow it to pass on through the intestinal tract.",
            "Medicated patches. If you think a child got hold of medicated patches — adhesive products for transdermal drug delivery — carefully inspect the child's skin and remove any that are attached. Also check the roof of the mouth, where medicated patches can get stuck if the child sucks on them."
        ],
        yt_url: "https://youtube.com/embed/b2ieb8BZJuY"
    }
];

export default firstAids;